title: sohee's blog
description: My Personal diary
author: Sohee Kim
github: https://github.com/agusmakmun
about: 쉽게만 살아가면 개재밌어 빙고
disqus_shortname: diary
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar_1.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-linkedin
      link: "https://www.instagram.com/__hang_in_there/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/ssoheekim"

share:
  twitter_username:
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: diary
      url: /diary/
url: "https://ssoheekim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']